// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_fpZSLrlhXaGbRVs2I1lpYd2CKkyDqM',
    appId: '1:819365687439:web:94e570cf86df06e5b9c0fa',
    messagingSenderId: '819365687439',
    projectId: 'app-cadastro-de-alunos-vf',
    authDomain: 'app-cadastro-de-alunos-vf.firebaseapp.com',
    storageBucket: 'app-cadastro-de-alunos-vf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWyPjF8JG0gJEE3d-W537McgNFNiJ1dc8',
    appId: '1:819365687439:android:08d1d24a69b7a784b9c0fa',
    messagingSenderId: '819365687439',
    projectId: 'app-cadastro-de-alunos-vf',
    storageBucket: 'app-cadastro-de-alunos-vf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJWssVNBvRv030t42zOMkDZt2nKU5zfc',
    appId: '1:819365687439:ios:4267b88b31154aa0b9c0fa',
    messagingSenderId: '819365687439',
    projectId: 'app-cadastro-de-alunos-vf',
    storageBucket: 'app-cadastro-de-alunos-vf.appspot.com',
    iosClientId: '819365687439-cmc3m54lg70ahq6e4hdv2aihhvvidrae.apps.googleusercontent.com',
    iosBundleId: 'com.example.appParcial',
  );
}
